---
# A simple role to install SWATCH log watcher
# This also gets rid of the previous files
# from the previous version of the role
# with the tag cleanup. Plan is run once
# then remove that code. Tagged: cleanup

  - name: Install all those dependencies
    apt: pkg={{item}} state=present
    with_items:
      - libbit-vector-perl
      - libcarp-clan-perl
      - libdate-calc-perl
      - libdate-calc-xs-perl
      - libfile-tail-perl
      - swatch
    tags:
      - swatch

  - name: Just make sure swatch is not already running
    command: /usr/bin/pkill -9 swatch
    ignore_errors: True
    tags:
      - swatch

  - name: Just blow out the old conf dir
    file:
      path=/etc/swatch
      state=absent
    tags:
      - cleanup

  - name: Blow out the old init script
    file:
      path=/etc/init.d/swatchd
      state=absent
    tags:
      - cleanup

  - name: make sure that swatch conf dir is there
    file:
      path=/etc/swatch
      state=directory
      owner=root
      group=root
    tags:
      - swatch

  - name: add the swatch init scripts
    template:
      src={{ item }}.init.j2
      dest=/etc/init.d/swatch_{{ item }}
      owner=root
      group=root
      mode=0755
    with_items: swatch_inits
    tags:
      - swatch

  - name: add in the slack swatch integration shell script
    template:
      src=slack-swatch.sh.j2
      dest=/usr/local/bin/slack-swatch.sh
      owner=root
      group=root
      mode=0755
    when: swatch_slack_channel is defined and swatch_slack_username is defined
    tags:
      - slack

  - name: add the swatch conf files
    template:
      src="{{ item }}.conf.j2"
      dest="/etc/swatch/{{ item }}.conf"
      owner=root
      group=root
      mode=0644
    with_items: swatch_confs
    tags:
      - swatch

  - name: add the Monit swatch conf files
    template:
      src="{{ item }}.monit.j2"
      dest="/etc/monit/conf.d/{{ item }}.conf"
      owner=root
      group=root
      mode=0700
    with_items: swatch_monits
    tags:
      - monit

  - name: stop swatch if it's already there
    service:
      name=swatch_{{ item }}
      state=stopped
    tags:
      - swatch
    with_items: monit_swatch
    ignore_errors: True

  - name: Just make sure swatch is not already running
    command: /usr/bin/pkill -9 swatch
    ignore_errors: True
    tags:
      - swatch

  - name: Now start swatch
    service:
      name=swatch_{{ item }}
      enabled=yes
      state=started
    with_items: swatch_inits
    tags:
      - swatch
